In [ ]:
#Numpy:
#python we have lists that serve the purpose of arrays,but they are slow to process.
#Numpy aims to provide an array object that is upto 50x faster than traditional python lists
#the array object in Numpy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
#Arrays are very frequently used in data science, where speed and resources are very important

In [1]:
!pip install numpy


In [3]:
import numpy as np  #import numpy as numpy


In [4]:
list=[2,3,4,5,9,8,45]#converting list into array with the help of numpy
l=np.array(list)
l

array([ 2,  3,  4,  5,  9,  8, 45])

In [5]:
#create array withthe help of numpy
t=np.array([2,3,4,5,6,7,23])
print(t)

[ 2  3  4  5  6  7 23]


In [19]:
#create multidimenstional array
#q-np.array([[2,3,4,5,6,7,23],[2,3,4,5,67,77,2],[82,3,4,5,86,7,23]])
a=np.array([[1,2,3],[4,5,6]])
# print(q)
print(a)

[[1 2 3]
 [4 5 6]]


In [20]:
#arange function in numpy
p=np.arange(0,50,5)
p

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [21]:
#arange function in numpy
p=np.arange(0,50,10)
p

array([ 0, 10, 20, 30, 40])

In [22]:
#arange function in numpy
p=np.arange(0,50,20)
p

array([ 0, 20, 40])

In [23]:
#linspace
#start value,end value,count of value that you wnat to print it
p=np.linspace(0,3,15)
p

array([0.        , 0.21428571, 0.42857143, 0.64285714, 0.85714286,
       1.07142857, 1.28571429, 1.5       , 1.71428571, 1.92857143,
       2.14285714, 2.35714286, 2.57142857, 2.78571429, 3.        ])

In [24]:
#linspace
p=np.linspace(0,10,15)
p

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [25]:
#linspace
p=np.linspace(3,10,5)
p

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [26]:
#ones 
#3 rows, 2 columns filled with one
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
#eye
#eye function return identity matrix or identity array 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
#eye function return identity matrix or identity array 
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [34]:
#diag extracts a diagonal element
q=[1,2,3,4,5,6,7]
np.diag(q)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [35]:
#create array using repeating list
np.array([1,2,3]*5)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [36]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [37]:
#combine array
p=np.ones([2,4],int) #array with value 1 
p

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [38]:
np.vstack([p,2*p])

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [39]:
np.vstack([p,3*p])

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [40]:
#if you want to print horizontally,create new column
np.hstack([p,1*p])

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [41]:
np.hstack([p,3*p])

array([[1, 1, 1, 1, 3, 3, 3, 3],
       [1, 1, 1, 1, 3, 3, 3, 3]])

In [46]:
x=np.array([1,2,3,4,5,6])
y=np.array([4,5,6,6,7,8])
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[ 5  7  9 10 12 14]
[-3 -3 -3 -2 -2 -2]
[ 4 10 18 24 35 48]
[0.25       0.4        0.5        0.66666667 0.71428571 0.75      ]


In [47]:
#.dot function to get the dot product
x.dot(y)

139

In [48]:
#.T transpose the array convert row to column and vice versa

z=np.array([x,y])
z


array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 6, 7, 8]])

In [49]:
z.T

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 6],
       [5, 7],
       [6, 8]])

In [52]:
x.sum()


21

In [53]:
x.max()


6

In [55]:
x.min()

1

In [56]:
x.mean()

3.5

In [57]:
x.argmax()#index having maximm element

5

In [58]:
x.argmin()


0

In [59]:
y.argmin()

0

In [60]:
#numpy subsetting
bmi=np.array([24,45,454,65,87])
bmi[bmi>23]#element greater than 23

array([ 24,  45, 454,  65,  87])