In [3]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [2]:
import numpy as np

print(np.__version__)



1.24.3


In [4]:
import numpy as np 
array=np.array([1,2,3,4,5,6])
print(array)
print(type(array))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [6]:
import numpy as np

arr = np.array(4)

print(arr)


4


In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [8]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)


[[1 2 3]
 [4 5 6]]


In [9]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [10]:
#ndim attribute that returns an integer that tells us how many dimensions the array have.
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=10)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
number of dimensions : 10


In [20]:
#slicing
#a[0,1,0:2]
#0 means [10,20,30],[40,50,60]
#1 means [70,80,90],[100,110,120]
#a[0,1,0:2] since 0 means [10,20,30],[40,50,60], 
#see next number which is 1 [40,50,60] now next see 0:2 then check in [40,50,60] where 0,1,2 index we need 0:2 thats means 40,50
#  a=np.array9[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]
#  a[0,1,0:2]
#answer is 
#[40,50]

In [29]:
import numpy as np
a=np.array([10,20,30,40,50,60])
print(a)
print("a[::]=", a[::])# by default its gonna be 0:0:1 which is start index ,stop index(length of array ) and 1
print("a[::2]=", a[::2])#here start will be printed which is 0 thats means 10 and difference is 2, it will skip 20 and print 30 and then 50 will be printed 
print("a[:4]=", a[:4])#here we are giving start index which is 0 and end index 4, it exclude 1
print("a[-1:]=",a[-1:])#last index value will be printed
print("a[-1::-1]=",a[-1::-1])

[10 20 30 40 50 60]
a[::]= [10 20 30 40 50 60]
a[::2]= [10 30 50]
a[:4]= [10 20 30 40]
a[-1:]= [60]
a[-1::-1]= [60 50 40 30 20 10]


In [35]:
b=np.array([[10,20,30,40],[50,60,70,80]])
print(b)
print("b[0,0:3]=",b[0,0:3])
print("b[1,2:]=",b[1,2:])
print("b[0:2,0:2]=",b[0:2,0:2])

[[10 20 30 40]
 [50 60 70 80]]
b[0,0:3]= [10 20 30]
b[1,2:]= [70 80]
b[0:2,0:2]= [[10 20]
 [50 60]]


In [36]:
c=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
print(c)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]


In [37]:
c=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
print(c)
print("c[1,0,0:2]=",c[1,0,0:2])

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
c[1,0,0:2]= [70 80]


In [40]:
c=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
# print(c)
print("c[1,1,0:2]=",c[1,1,0:2])

c[1,1,0:2]= [100 110]


In [43]:
c=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
# print(c)
print("c[1,1,-1::-1]=",c[1,1,-1::-1])

c[1,1,-1::-1]= [120 110 100]


In [45]:
c=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
# print(c)
print("c[0:2,0:2,0:2]=",c[0:2,0:2,0:2])

c[0:2,0:2,0:2]= [[[ 10  20]
  [ 40  50]]

 [[ 70  80]
  [100 110]]]
