In [4]:
import numpy as np 
a = np.array([10,20,30])
print(a.dtype)

int32


In [10]:
import numpy as np

a=np.array([10,20,30],dtype=np.uint32)

In [11]:
import numpy as np

a=np.array([10,20,30],dtype="f")

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)


[1 2 3 4]
int32


In [19]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')#

print(newarr)
print(newarr.dtype)


[1 2 3]
int32


In [20]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[1 2 3 4 5]


In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[42  2  3  4  5]


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)


None
[1 2 3 4 5]


In [25]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)


(2, 4)


In [41]:
#basic of Numpyor creation of ndarray
import numpy
a=numpy.array([1,2,3])
b=numpy.array(54)
c=numpy.array([[1,2,3],[4,5,6]])#2 dimentions array
d=numpy.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,2]]]) 
print(a)
print(b)
print(c)
print(d)
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(type(a))
print(type(b))



[1 2 3]
54
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 2]]]
1
0
2
3
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [45]:
#ASARRAY( ) , FROMBUFFER( ) , FROMITER( ) IN NUMPY (ARRAYS WITH EXISTING DATA) - PYTHON PROGRAMMING
#arrays with existing data 
#asarray(input(list,tuple,any combination),dtype(int,float),order(row major"C",column major"F"))
#order(row major"C",column major"F"[[10,20,30]
#                                   [40,50,60]]
#R.M -10,20,30,40,50,60 ROW MEASURE
#COLUMN MEASURE C.M -10 40 20 50 30 60

l=[10,20,30]#list
A=[10 20 30]#array
import numpy as np 
np.asarray(l,dtype="float",order="")
#nditer()


In [52]:
#frombuffer(buffer,dtype,count,offset)
#create an array with given datatype of given length from given position
import numpy as np
s=b"Welcome"
result_array=np.frombuffer(s, dtype="S1",count=-1,offset=0) #by default count=-1
print(result_array)


[b'W' b'e' b'l' b'c' b'o' b'm' b'e']


In [53]:
import numpy as np
s=b"Welcome"
result_array=np.frombuffer(s, dtype="S1",count=3,offset=0)
#by default count=-1
#offset means where starting point to abstract
print(result_array)

[b'W' b'e' b'l']


In [55]:
import numpy as np
s=b"Welcome"
result_array=np.frombuffer(s, dtype="S1",count=3,offset=3) #by default count=-1
print(result_array)

[b'c' b'o' b'm']


In [64]:
#fromiter(sequence can ne considered as iter)
#fromiter(iterable(list,tuple),dtype(int,float),count(lemgth of returned array , by default count=-1))
import numpy as np
t=(10,20,30)
result_array=np.fromiter(t,dtype="float", count=-1)
print(result_array)

[10. 20. 30.]


In [66]:
import numpy as np
t=(10,20,30)
result_array=np.fromiter(t,dtype=int)
print(result_array)

[10 20 30]


In [68]:
import numpy as np
t=(10,20,30)
result_array=np.fromiter(t,dtype="float", count=2)
print(result_array)

[10. 20.]


In [69]:
import numpy as np
a=np.array([10,20,30,40,50,60])
print(a)

[10 20 30 40 50 60]


In [70]:
res=np.asarray(a,dtype="float",order="C")
print(res)

[10. 20. 30. 40. 50. 60.]


In [71]:
b=np.array([[10,20,30],[40,50,60]])
print(b)

[[10 20 30]
 [40 50 60]]


In [75]:
res1=numpy.asarray(b,dtype="int",order="F")
res1=np.asarray(b,dtype="int",order="F")
print(res1)

[[10 20 30]
 [40 50 60]]


In [77]:
for i in np.nditer(res1):
    print(i)

10
40
20
50
30
60


In [82]:
res2=np.asarray(b,dtype="int",order="C")
for i in np.nditer(res2):
    print(i)
  

10
20
30
40
50
60


In [83]:
print(res2)

[[10 20 30]
 [40 50 60]]


In [84]:
s=b"hello welcome to python"

In [86]:
c=np.frombuffer(s,dtype="S1",count=-1, offset=0)
print(c)

[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'e' b'l' b'c' b'o' b'm' b'e' b' '
 b't' b'o' b' ' b'p' b'y' b't' b'h' b'o' b'n']


In [88]:
c=np.frombuffer(s,dtype="S1",count=10, offset=0)
print(c)

[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'e' b'l' b'c']


In [90]:
list=[10,20,30,40,50]
d=np.fromiter(list,dtype="float",count=-1)
print(d)

[10. 20. 30. 40. 50.]


In [92]:
list=[10,20,30,40,50]
d=np.fromiter(list,dtype="S1",count=-1)
print(d)

[b'1' b'2' b'3' b'4' b'5']


In [94]:
list=[10,20,30,40,50]
d=np.fromiter(list,dtype="S1",count=2)
print(d)

[b'1' b'2']


In [95]:
list=[10,20,30,40,50]
d=np.fromiter(list,dtype="float",count=2)
print(d)

[10. 20.]
